# Generated by Django 3.0 on 2019-12-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20191229_2216'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pilot',
            constraint=models.UniqueConstraint(fields=('race', 'bike_name'), name='name of constraint'),
        ),
    ]
